name: Publish to Docker

on:
  release:
    types: [published]
  
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Publish and push the container image
        run: |
          dotnet publish --os linux --arch x64 /t:PublishContainer -c Release -p ContainerImageTags='"${{ github.event.release.name }};latest"'
        working-directory: .